application: howmanyhadoops
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  application_readable: true

- url: /.*
  script: howmanyhadoops.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest